param(
    [string]$BridgeHome = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
    [string]$MotionBuilderVersion = "2024",
    [ValidateSet("User", "System", "All")]
    [string]$Scope = "User",
    [switch]$AutoStartBridge,
    [switch]$OpenPanel
)

$ErrorActionPreference = "Stop"

$BridgeHome = (Resolve-Path -LiteralPath $BridgeHome).Path
if (-not (Test-Path -LiteralPath (Join-Path $BridgeHome "py\mb_bridge_server.py"))) {
    throw "BridgeHome does not look like MotionBuilderBridge: $BridgeHome"
}

function Get-StartupTargets {
    param(
        [string]$Version,
        [string]$TargetScope
    )

    $targets = @()
    if ($TargetScope -in @("User", "All")) {
        $targets += [PSCustomObject]@{
            Scope = "UserDocumentsVersioned"
            Path = Join-Path $env:USERPROFILE "Documents\MB\$Version\config\PythonStartup"
            RequiresAdmin = $false
        }
        $targets += [PSCustomObject]@{
            Scope = "UserRoaming"
            Path = Join-Path $env:APPDATA "Autodesk\MotionBuilder\config\PythonStartup"
            RequiresAdmin = $false
        }
        $targets += [PSCustomObject]@{
            Scope = "UserDocumentsGlobal"
            Path = Join-Path $env:USERPROFILE "Documents\MB\PythonStartup"
            RequiresAdmin = $false
        }
    }

    if ($TargetScope -in @("System", "All")) {
        $targets += [PSCustomObject]@{
            Scope = "System"
            Path = Join-Path ${env:ProgramFiles} "Autodesk\MotionBuilder $Version\bin\config\PythonStartup"
            RequiresAdmin = $true
        }
    }

    return $targets
}

$bridgeHomePy = $BridgeHome.Replace("\", "/")

$lines = @(
    "# Auto-generated by MotionBuilderBridge tools/install_mobu_startup.ps1",
    "import os, sys",
    "BRIDGE_HOME = r'$bridgeHomePy'",
    "PY_DIR = os.path.join(BRIDGE_HOME, 'py')",
    "if PY_DIR not in sys.path:",
    "    sys.path.insert(0, PY_DIR)",
    "os.environ.setdefault('MOTIONBUILDER_BRIDGE_HOME', BRIDGE_HOME)"
)

if ($AutoStartBridge) {
    $lines += @(
        "from mb_bridge_server import start_bridge",
        "start_bridge()"
    )
}

$showPanel = if ($OpenPanel) { "True" } else { "False" }
$lines += @(
    "import mb_bridge_tool",
    "mb_bridge_tool.register_tool(auto_start=False, show=$showPanel)"
)

$installed = @()
foreach ($target in Get-StartupTargets -Version $MotionBuilderVersion -TargetScope $Scope) {
    if (-not (Test-Path -LiteralPath $target.Path)) {
        New-Item -ItemType Directory -Force -Path $target.Path | Out-Null
    }

    $loader = Join-Path $target.Path "MotionBuilderBridge_startup.py"
    try {
        Set-Content -LiteralPath $loader -Value ($lines -join [Environment]::NewLine) -Encoding UTF8
        $installed += $loader
        Write-Host "Installed MotionBuilder startup loader [$($target.Scope)]: $loader"
    } catch [System.UnauthorizedAccessException] {
        if ($target.RequiresAdmin) {
            Write-Warning "Could not write system startup loader because administrator permission is required: $loader"
            Write-Warning "Re-run PowerShell as Administrator, or use -Scope User."
        } else {
            throw
        }
    }
}

if (-not $installed) {
    throw "No startup loaders were installed."
}

if (-not $AutoStartBridge -and -not $OpenPanel) {
    Write-Host "Loader only adds MotionBuilderBridge to sys.path. Re-run with -AutoStartBridge and/or -OpenPanel for automatic startup."
}
