param(
    [string]$BridgeHome = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
    [string]$MotionBuilderVersion = "2024",
    [switch]$AutoStartBridge,
    [switch]$OpenPanel
)

$ErrorActionPreference = "Stop"

$BridgeHome = (Resolve-Path -LiteralPath $BridgeHome).Path
if (-not (Test-Path -LiteralPath (Join-Path $BridgeHome "py\mb_bridge_server.py"))) {
    throw "BridgeHome does not look like MotionBuilderBridge: $BridgeHome"
}

$startupDir = Join-Path ${env:ProgramFiles} "Autodesk\MotionBuilder $MotionBuilderVersion\bin\config\PythonStartup"
if (-not (Test-Path -LiteralPath $startupDir)) {
    throw "MotionBuilder PythonStartup folder not found: $startupDir"
}

$loader = Join-Path $startupDir "MotionBuilderBridge_startup.py"
$bridgeHomePy = $BridgeHome.Replace("\", "/")

$lines = @(
    "# Auto-generated by MotionBuilderBridge tools/install_mobu_startup.ps1",
    "import os, sys",
    "BRIDGE_HOME = r'$bridgeHomePy'",
    "PY_DIR = os.path.join(BRIDGE_HOME, 'py')",
    "if PY_DIR not in sys.path:",
    "    sys.path.insert(0, PY_DIR)",
    "os.environ.setdefault('MOTIONBUILDER_BRIDGE_HOME', BRIDGE_HOME)"
)

if ($AutoStartBridge) {
    $lines += @(
        "from mb_bridge_server import start_bridge",
        "start_bridge()"
    )
}

if ($OpenPanel) {
    $lines += @(
        "import mb_bridge_tool",
        "mb_bridge_tool.show_tool()"
    )
}

Set-Content -LiteralPath $loader -Value ($lines -join [Environment]::NewLine) -Encoding UTF8
Write-Host "Installed MotionBuilder startup loader: $loader"

if (-not $AutoStartBridge -and -not $OpenPanel) {
    Write-Host "Loader only adds MotionBuilderBridge to sys.path. Re-run with -AutoStartBridge and/or -OpenPanel for automatic startup."
}
